import {IProduct} from '../../Models/IProduct';

export const ProductsData: Array<IProduct> = [
    {
        id: 0,
        name: 'Tomatoes',
        price: 3,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/tomatoes_4t2p_FNe5.jpg?updatedAt=1628805672740',
        alt: 'tomatoes',
    },
    {
        id: 1,
        name: 'Giant Tomatoes',
        price: 5,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/giantTomatoes_Ms4eYLXhu.jpg?updatedAt=1628805613687',
        alt: 'tomatoes',
        newPrice: 3,
    },
    {
        id: 2,
        name: 'Raspberry Tomatoes',
        price: 4,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/raspberryTomatoes_1qJwd5HSz.jpg?updatedAt=1628805613724',
        alt: 'tomatoes',
        newPrice: 2,
    },
    {
        id: 3,
        name: 'Dark Sweet Grapes',
        price: 5,
        per: 'kg',
        img: "https://ik.imagekit.io/kacper/green-world/darkSweetGrapes_Y7lOoFetxI.jpg?updatedAt=1628794762905",
        alt: "grapes",
        newPrice: 4,
    },
    {
        id: 3,
        name: 'Potato',
        price: 1,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/potato_nOvZRsPU1cR.jpg?updatedAt=1628802628089',
        alt: 'potatoes in hands',
    },
    {
        id: 4,
        name: 'Onion',
        price: 1,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/onions_FdXeItT5ukI.jpg?updatedAt=1628802627750',
        alt: 'onions on table',
    }, {
        id:5,
        name: 'Blackberries',
        price: 7,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/blackberries_S4I_5BAzcq.jpg?updatedAt=1628802627237',
        alt: 'Blackberry on hands',
        newPrice: 4,
    }, {
        id: 6,
        name: 'Strawberries',
        price: 5,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/strawberry_5iHA1XfrD.jpg?updatedAt=1628802627323',
        alt: 'Strawberries on hands',
        newPrice: 4,
    }, {
        id: 7,
        name: 'Cherries',
        price: 7,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/cherry_h9ONJsBL0Y.jpg?updatedAt=1628802627309',
        alt: 'Cherries on hands',
    }, {
        id: 8,
        name: 'Cucumber',
        price: 1,
        per: '1',
        img: 'https://ik.imagekit.io/kacper/green-world/cucumber_hlbfiXfPms.jpg?updatedAt=1628802627969',
        alt: 'cucumbers in in the basket',
    }, {
        id: 9,
        name: 'Radishes',
        price: 2,
        per: 'bunch',
        img: 'https://ik.imagekit.io/kacper/green-world/radish_Nzu-Bafxm.jpg?updatedAt=1628802627246',
        alt: 'radish on black background',
        newPrice: 1,
    },
    {
    id: 10,
    name: 'Peas',
    price: 5,
    per: 'kg',
    img: 'https://ik.imagekit.io/kacper/green-world/peas_1YSOO64Xzx.jpg?updatedAt=1628803781319',
    alt: 'Peas on hands',
},
    {
        id: 11,
        name: 'Spinach',
        price: 4,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/spinach_IcX6ggrjIt.jpg?updatedAt=1628803781185',
        alt: 'a bunch of spinach',
    },    {
        id: 12,
        name: 'Avocado',
        price: 3,
        per: '1',
        img: 'https://ik.imagekit.io/kacper/green-world/avocado_QuOsInSJc_F.jpg?updatedAt=1628803780799',
        alt: 'Avocados in the plate',
    },    {
        id: 13,
        name: 'Cabbage',
        price: 3,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/cabbage_v-MaRyTXDS.jpg?updatedAt=1628803780629',
        alt: 'Cabbage on the desk',
    },    {
        id: 14,
        name: 'Cauliflower',
        price: 4,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/cauliflower_5wCv-MQ8O.jpg?updatedAt=1628803780745',
        alt: 'Cauliflower on the desk',
        newPrice: 3,
    },    {
        id:15 ,
        name: 'Beetroot',
        price: 3,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/beetroot_vUmyACaJAJ.jpg?updatedAt=1628803780848',
        alt: 'Beetroots on the desk',
    },    {
        id:16 ,
        name: 'Lettuce',
        price: 3,
        per: 'kg',
        img: 'https://ik.imagekit.io/kacper/green-world/lettuce_-b8bbE0gJ.jpg?updatedAt=1628803780500',
        alt: 'Lettuce on dark background',
        newPrice: 2,
    },
]